# Generated by Django 5.0.6 on 2024-05-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authorisation', '0002_userotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='companyName',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='companySize',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='language',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='primaryInterest',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
